### ISSUE TITLE
information missed, if it is possible to use pip to install additional moduls

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/sql-docs.de-de#100]
Normally python can by extended by installing additional modules using pip.
I suggest to add some information if this is also the case for the sql server indatabase installation or if only the delivered modules can be used.
If it is possible to extend the installation then some words how to do would be fine.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 51af6932-4881-c82d-c43a-cd4552f33129
* Version Independent ID: 637b37f1-be16-9761-9eb1-eabcdde0a1d2
* Content: [Erweiterung der Python-Programmiersprache - SQL Server Machine Learning Services](https://docs.microsoft.com/de-de/sql/advanced-analytics/concepts/extension-python?view=sql-server-2017)
* Content Source: [docs/advanced-analytics/concepts/extension-python.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/advanced-analytics/concepts/extension-python.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by srvbpigh** [comment]
Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by aisbergde** [comment]
I see, it is possible. But a link to this information is missing.
Would be better if you add a link to this page, then it will be clear that it can be extended and how.
https://docs.microsoft.com/de-de/sql/advanced-analytics/package-management/install-additional-python-packages-on-sql-server?view=sql-server-2017

**Comment by dphansen** [comment]
@aisbergde As described in [Install Python packages with sqlmlutils](https://docs.microsoft.com/en-us/sql/advanced-analytics/package-management/install-additional-python-packages-on-sql-server?view=sql-server-2017):

> The standard Python pip install command is not recommended for adding Python packages on SQL Server. Instead, use sqlmlutils as described in this article.

As the `pip install` command is not recommended, we will not add this to our documentation.

@CeciAc #please-close

**Comment by dphansen** [comment]
@aisbergde Thank you for your suggestion in the comment above. I have added the link under "next steps" to the article. PR https://github.com/MicrosoftDocs/sql-docs-pr/pull/12215

**Comment by aisbergde** [comment]
I already understand that it is useless to suggest any improvements to the documentation. I suggest to add a link to the place where the user can read what you write. Because if a user is here in this place of the documentation how you should know that pip is not supported I you don't add a link to the place where this is written?
The result is often the same: there is a very detaild Microsoft documentation, but links between items, which are required to get the whole picture, are missing. Finally a user will find this information not, using Microsoft documentation, but external search engines. Why I spent my time to suggest improvements if the standard answer is: "we will nothing change because we know better"? Why asking for feedback if you don't care?

**Comment by lichasu** [comment]
Closing as requested
