### ISSUE TITLE
example to import sqlmlutils uses sql user, add instruction how to use a connection with integrated security

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/sql-docs.de-de#101]
Microsofts recomandation is not to use SQL user but integrated security and to disable sql user. So please also add an example how to use integrated security.
If this is not possible then please write in the documentation that the import is only possible with sql user enabled.

import sqlmlutils
connection = sqlmlutils.ConnectionInfo(server="yourserver", database="yourdatabase", uid="yoursqluser", pwd="yoursqlpassword")
sqlmlutils.SQLPackageManager(connection).install("text-tools")

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: bb790fba-2d19-b1a7-3935-6ec5f9207fcc
* Version Independent ID: f350cf6b-0fa8-6d76-8433-f3f752e62ecf
* Content: [Installieren von Python-Paketen mit PIP - SQL Server Machine Learning Services](https://docs.microsoft.com/de-de/sql/advanced-analytics/package-management/install-additional-python-packages-on-sql-server?view=sql-server-2017)
* Content Source: [docs/advanced-analytics/package-management/install-additional-python-packages-on-sql-server.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/advanced-analytics/package-management/install-additional-python-packages-on-sql-server.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @garyericson
* Microsoft Alias: **garye**

**Comment by srvbpigh** [comment]
Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by dphansen** [comment]
@aisbergde Thank you for your suggestion. I have added this to our internal backlog and we will add this to the how-to guide for sqlmlutils.

@CeciAc Please close this GitHub issue.

**Comment by lichasu** [comment]
Closing as requested.
