### ISSUE TITLE
CROSS APPLY OPENJSON examples are hard to understand and to reproduce if the content of the JSON strings is unknown

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/sql-docs.de-de#102]
On this site are some examples for the usage of CROSS APPLY.
But these examples are very hard to understand and can't be reproduced if the content of the JSON is unknown.
Please consider to add the content of the used JSON strings to enable a user to understand examples.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e25eda30-d6e4-600c-ed9d-4f0a53ee1058
* Version Independent ID: 9b53b7d7-b827-6f7f-c0c9-84645742d6a2
* Content: [OPENJSON (Transact-SQL) - SQL Server](https://docs.microsoft.com/de-de/sql/t-sql/functions/openjson-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/functions/openjson-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/t-sql/functions/openjson-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by srvbpigh** [comment]
Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Issue moved to [MicrosoftDocs/sql-docs #3081](https://github.com/MicrosoftDocs/sql-docs/issues/3081) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lichasu** [comment]
Hello, @aisbergde ,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/sql-docs/issues/3081.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
