### ISSUE TITLE
Falsche Links

### ISSUE THREAD

**Issue by Xandolph** [MicrosoftDocs/sql-docs.de-de#104]
Die Downloadlinks führen alle zu www.microsoft.com, das Produkt kann nicht heruntergeladen werden!

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Herunterladen von SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/de-de/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by srvbpigh** [comment]
Hello, @Xandolph
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by mamosoft** [comment]
Hi @srvbpigh
have you an idea, when the issue with the download link will be fixed?

**Comment by x-0-r** [comment]
The correct link would be https://go.microsoft.com/fwlink/?linkid=2105412

**Comment by CeciAc** [comment]
Hallo, @Xandolph

Vielen Dank für Ihr Feedback. 

Unsere Technikexperten haben sich Ihre Vorschläge angesehen und für gut befunden. Wir haben Ihr Feedback implementiert und im aktualisierten Artikel auf der Dokumentationsseite unter folgender Seite veröffentlicht: https://docs.microsoft.com/de-de/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback
Vielen Dank für Ihren Beitrag zu diesem Artikel. Gerne können Sie auch weiterhin Feedback zu anderen Artikeln abgeben. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
