### ISSUE TITLE
instruction or link: how to clone an existing Git-Repo which is not yet cloned to a local directory, using Azure Data Studio

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/sql-docs.de-de#105]
I miss information how to clone an existing Git-Repository (for example on dev.azure.com, on github, ...) using only Azure Data Studio. Or if this is not possible with Azure Data Studio: A link or some instructions how to start.
Normally I use Visual Studio to clone and manage Git-Repos, but there are environments where VS can't be installed, but Azure Data Studio works fine.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a4e4bf78-49f5-ecce-a9bd-d89efab80063
* Version Independent ID: 805d36d2-8163-48be-1a02-55008b4b09f7
* Content: [Quellcodeverwaltung - Azure Data Studio](https://docs.microsoft.com/de-de/sql/azure-data-studio/source-control?view=sql-server-2017)
* Content Source: [docs/azure-data-studio/source-control.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/azure-data-studio/source-control.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by srvbpigh** [comment]
Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Issue moved to [MicrosoftDocs/sql-docs #3221](https://github.com/MicrosoftDocs/sql-docs/issues/3221) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lichasu** [comment]
Hello, @aisbergde ,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/sql-docs/issues/3221.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
