### ISSUE TITLE
missing instruction how to download or create an offline setup for SQL Server Developer Edition

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/sql-docs.de-de#106]
I can't find some information how to download or create an offline setup for SQL Server Developer Edition. The download button will only download a small online installer.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4ae75dfb-2017-17a3-835b-9409fdb06427
* Version Independent ID: 8f22b559-823e-d719-7c5d-f76f89345c01
* Content: [Installieren von SQL Server - SQL Server](https://docs.microsoft.com/de-de/sql/database-engine/install-windows/install-sql-server?view=sql-server-ver15)
* Content Source: [docs/database-engine/install-windows/install-sql-server.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/database-engine/install-windows/install-sql-server.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by srvbpigh** [comment]
Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by MashaMSFT** [comment]
Hi @aisbergde , I believe the free edition should be at this link: Kostenlose Editionen finden Sie unter [SQL Server-downloads](https://www.microsoft.com/sql-server/sql-server-downloads).  

It should take you to this page, where you'll see the developer edition:
![image](https://user-images.githubusercontent.com/32783170/66776589-903fd000-ee7b-11e9-9e31-cac4d1a3934e.png)
Link: https://go.microsoft.com/fwlink/?linkid=853016 

Once you launch that, you should be able to choose the "Download media" option after you execute the .exe: 
![image](https://user-images.githubusercontent.com/32783170/66776644-bb2a2400-ee7b-11e9-8a03-df329fe29a5d.png)

I hope that helps and please us know if you continue experiencing an issue?

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @aisbergde , since we haven't heard from you, we'll assume your issue is resolved. Please let us know if you need anything further :)

Thanks!
Masha from the SQL Docs team
#please-close
