### ISSUE TITLE
Please Fix the parameters tables

### ISSUE THREAD

**Issue by Lycrosa** [MicrosoftDocs/sql-docs.de-de#112]
Hey the tables contain some major formating erros wich makes them reaalllyy hard to read

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4ff01c71-f3bf-2c3a-5e90-b11952aee4f8
* Version Independent ID: 99ebd80b-9465-6929-c84f-187525ee3284
* Content: [SQL Server-Installation: Eingabeaufforderungsparameter - SQL Server](https://docs.microsoft.com/de-de/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?redirectedfrom=MSDN&view=sql-server-ver15)
* Content Source: [docs/database-engine/install-windows/install-sql-server-from-the-command-prompt.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/database-engine/install-windows/install-sql-server-from-the-command-prompt.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by srvbpigh** [comment]
Hello, @Lycrosa
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by MashaMSFT** [comment]
Hi @srvbpigh , thanks for bringing this to our attention! It looks like the formatting issue has been fixed. Can you please confirm that you're no longer seeing it on your end?

Thanks!
Masha from the SQL Docs team

**Comment by srvbpigh** [comment]
Vielen Dank für Ihr Feedback.  

Unsere Technikexperten haben sich Ihre Vorschläge angesehen und für gut befunden. Wir haben Ihr Feedback implementiert und im aktualisierten Artikel auf der Dokumentationsseite unter folgender Seite veröffentlicht: https://docs.microsoft.com/de-de/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?redirectedfrom=MSDN&view=sql-server-ver15.   

Vielen Dank für Ihren Beitrag zu diesem Artikel. Gerne können Sie auch weiterhin Feedback zu anderen Artikeln abgeben.  

Mit freundlichen Grüßen  
das Microsoft DOCS International Team
