### ISSUE TITLE
Error in german translation for the Simple Recovery Model Description

### ISSUE THREAD

**Issue by MarcNetto** [MicrosoftDocs/sql-docs.de-de#113]
The sentence "Die folgenden Funktionen können beim einfachen Wiederherstellungsmodus verwendet werden:" is wrong, it has to be "Die folgenden Funktionen können beim einfachen Wiederherstellungsmodus nicht verwendet werden:". See the original text in english: "... cannot...".

**Comment by srvbpigh** [comment]
Hello, @MarcNetto
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hallo, @MarcNetto,

Wir freuen uns über Ihren Kommentar und bemühen uns, Ihre Erfahrungen mit docs.microsoft.com zu verbessern. Wir benötigen jedoch weitere Informationen, um auf Ihr Feedback eingehen zu können. Können Sie uns bitte nähere Informationen geben und Ihren Kommentar erläutern? 

Mit freundlichen Grüßen 

Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
@MarcNetto please provide URL where you spotted this issue.

Kind regards,

Microsoft DOCS Global Experience Team

**Comment by MarcNetto** [comment]
If you search for "Simple Recovery Model" the first result is the URL you need.
Here it is: https://docs.microsoft.com/de-de/sql/relational-databases/backup-restore/recovery-models-sql-server?view=sql-server-ver15

**Comment by ticianaciminari** [comment]
Hello, @MarcNetto,

Thank you for your feedback. 

Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/sql/relational-databases/backup-restore/recovery-models-sql-server?view=sql-server-ver15.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 

Microsoft DOCS International Team
