### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by Downvote-Hunter** [MicrosoftDocs/sql-docs.de-de#114]
Rename mastlog.mdf to mastlog.ldf

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b12eac8a-8797-b2d4-5195-e1d77b4b0001
* Version Independent ID: 163b4b50-6e25-b006-6ea6-c6e4cfd044d0
* Content: [Konfigurieren von Umgebungsvariablen für SQL Server für Linux - SQL Server](https://docs.microsoft.com/de-de/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-linux-2017)
* Content Source: [docs/linux/sql-server-linux-configure-environment-variables.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/linux/sql-server-linux-configure-environment-variables.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by srvbpigh** [comment]
Hello, @Downvote-Hunter
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hallo, @Downvote-Hunter,   

Vielen Dank für Ihr Feedback.  

unsere Sprachexperten haben sich Ihren Vorschlag angesehen und diesen für gut befunden. Wir haben Ihr Feedback implementiert und im aktualisierten Artikel auf der Dokumentationsseite unter folgender Seite veröffentlicht: https://docs.microsoft.com/de-de/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-linux-2017.   

Vielen Dank für Ihren Beitrag zu diesem Artikel. Gerne können Sie auch weiterhin Feedback zu anderen Artikeln abgeben.  

Mit freundlichen Grüßen  
das Microsoft DOCS International Team

**Comment by Downvote-Hunter** [comment]
It's still mastlog.mdf in the german version.

**Comment by ticianaciminari** [comment]
Hello, @Downvote-Hunter,

Thank you for your feedback. 

Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages XXX.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 

Microsoft DOCS International Team
