### ISSUE TITLE
Registry error

### ISSUE THREAD

**Issue by SecureString** [MicrosoftDocs/sql-docs.de-de#115]
Bei Verwendung der DSC Resource SQL Setup erhalte ich eine Vielzahl von Registry Fehlern in der Form:
Cannot find path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\Instance Names\SQL' because it does not exist.
Was könnte die Ursache sein?
Vielen Dank für jede Idee

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4077fc1c-b803-5a78-8f5b-0fdcb760f29e
* Version Independent ID: 3550efe5-2c8d-79d8-3bc6-4d3bed923d03
* Content: [Installation: PowerShell Desired State Configuration - SQL Server](https://docs.microsoft.com/de-de/sql/database-engine/install-windows/install-sql-server-with-powershell-desired-state-configuration?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/install-windows/install-sql-server-with-powershell-desired-state-configuration.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/database-engine/install-windows/install-sql-server-with-powershell-desired-state-configuration.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @randomnote1
* Microsoft Alias: **dareist**

**Comment by srvbpigh** [comment]
Hello, @SecureString
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/sql-docs #4148](https://github.com/MicrosoftDocs/sql-docs/issues/4148) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hallo, @SecureString,  

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation.  

Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/sql-docs/issues/4148.  

Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.   

Mit freundlichen Grüßen  
das Microsoft DOCS International Team
