### ISSUE TITLE
Markdown Format

### ISSUE THREAD

**Issue by jonkas2211** [MicrosoftDocs/sql-docs.de-de#118]
The format of the markdown seems to be invalid. It is not formated and the raw markdown is show.
Content copied of the middle of the document to demonstrate what users see:
rowset exhibiting immediate update behavior. Other properties are mutually exclusive. For example, a rowset exhibiting DBPROP_OTHERINSERT cannot contain bookmarks. |Property ID|Value|Rowset behavior| |-----------------|-----------|---------------------| |DBPROP_SERVERCURSOR|VARIANT_TRUE|Cannot update [!INCLUDE[ssNoVersion](../../includes/ssnoversion-md.md)] data through the rowset.
...

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b486b034-fb7b-0e24-9730-49977922cd51
* Version Independent ID: 3ec7ec8c-b228-c6fa-4c91-0b34c57fd0a8
* Content: [Rowsets und SQL Server Cursor - SQL Server](https://docs.microsoft.com/de-de/sql/relational-databases/native-client-ole-db-rowsets/rowsets-and-sql-server-cursors?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/native-client-ole-db-rowsets/rowsets-and-sql-server-cursors.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/relational-databases/native-client-ole-db-rowsets/rowsets-and-sql-server-cursors.md)
* Product: **sql**
* Technology: **native-client**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by srvbpigh** [comment]
Hello, @jonkas2211
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @jonkas2211 

Thank you for your contribution.

Contributions on translation problems against machine translated content are currently not accepted.

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations.

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file.

Many thanks for your support.

Microsoft DOCS Global Experience Team

**Comment by MightyPen** [comment]
@RyanKing77 Hi Ryan, I believe your Localization team is aware of some other bugs similar to this Issue #118 , wherein raw markdown source code is displayed on the live Docs render of the article.

If so, maybe you have a little info you could add to this Issue in a another Comment box.

---

@jonkas2211 Hello, I very much value your feedback here about this German (de-de/) edition of this article.  This de-de edition is currently rendering very poorly, which is something we must work to correct.
We here at Microsoft believe we have a little flaw in our Localization system, as you pointed out by taking the time to create this Issue #118 for us.  I believe work has begun toward fixing this problem.  However, I cannot estimate a date by when this will be fixed.

We are in the process of improving our Machine Translation subsystem.  Apparently the improvements also suffer a little flaw, and the flaw has unusually large negative effect on the display of some articles.

Thanks again for bringing this display flaw to our attention.  There is now plenty of awareness of the Issue you have raised, so I will leave this #118 Closed.

---

Thanks. G

cc: @srvbpigh @CeciAc
