### ISSUE TITLE
Übersetzungsfehler Translation Error

### ISSUE THREAD

**Issue by MunniDerMeister** [MicrosoftDocs/sql-docs.de-de#119]
In der deutschen Version fehlt bei der Beschreibung des Wiederherstellungsmodells das durchaus wichtige Wort "nicht". 
Die folgenden Funktionen können beim einfachen Wiederherstellungsmodus NICHT verwendet werden:

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4c4e8f86-1fea-7513-344b-7d3b71378619
* Version Independent ID: d07c2ded-4e5b-2420-b8ab-5b9d085f0de4
* Content: [Wiederherstellungsmodelle (SQL Server) - SQL Server](https://docs.microsoft.com/de-de/sql/relational-databases/backup-restore/recovery-models-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/backup-restore/recovery-models-sql-server.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/relational-databases/backup-restore/recovery-models-sql-server.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by srvbpigh** [comment]
Hello, @MunniDerMeister
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hallo, @MunniDerMeister,   

Vielen Dank für Ihr Feedback.  

unsere Sprachexperten haben sich Ihren Vorschlag angesehen und diesen für gut befunden. Wir haben Ihr Feedback implementiert und im aktualisierten Artikel auf der Dokumentationsseite unter folgender Seite veröffentlicht: https://docs.microsoft.com/de-de/sql/relational-databases/backup-restore/recovery-models-sql-server?view=sql-server-ver15#feedback.   

Vielen Dank für Ihren Beitrag zu diesem Artikel. Gerne können Sie auch weiterhin Feedback zu anderen Artikeln abgeben.  

Mit freundlichen Grüßen  
das Microsoft DOCS International Team
