### ISSUE TITLE
Images in the docs don't work in dark mode

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/sql-docs.de-de#120]
Many pictures in the SQL Server docs have been created with a transparent background.

Due to the transparent background, black letters in the image render illegible in dark mode:

![Screenshot](https://user-images.githubusercontent.com/9283914/79081357-f4edc180-7d1c-11ea-9cf0-969a8a11df34.png)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 9a878f81-f084-d4a2-8098-2b63558b7369
* Version Independent ID: 9e64bd2c-670e-284b-f34e-a409650cec88
* Content: [Handbuch zur Architektur und Verwaltung von Transaktionsprotokollen - SQL Server](https://docs.microsoft.com/de-de/sql/relational-databases/sql-server-transaction-log-architecture-and-management-guide?view=sql-server-ver15#physical_arch)
* Content Source: [docs/relational-databases/sql-server-transaction-log-architecture-and-management-guide.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/relational-databases/sql-server-transaction-log-architecture-and-management-guide.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by srvbpigh** [comment]
Hello, @SetTrend
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/sql-docs #4542](https://github.com/MicrosoftDocs/sql-docs/issues/4542) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @SetTrend, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/sql-docs/issues/4542. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
