### ISSUE TITLE
Leben Oh ne depperte Nachbaren

### ISSUE THREAD

**Issue by christian7877** [MicrosoftDocs/sql-docs.de-de#122]
Tutorial: SQL Server Management Studio
Dokumentation zu SQL Server Management Studio
Neueste Updates
Azure Data Studio
Download der neuesten SQL Server-Datatools
Azure-Datenarchitekturleitfaden

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Herunterladen von SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/de-de/sql/ssms/download-sql-server-management-studio-ssms?redirectedfrom=MSDN&view=sql-server-ver15)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by srvbpigh** [comment]
Hello, @christian7877
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @christian7877 

Ihre Kommentare verstoßen gegen unsere Verhaltensregeln unter https://opensource.microsoft.com/codeofconduct/.

Deshalb sperren und schließen wir dieses Problem.

Mit freundlichen Grüßen

das Microsoft DOCS International Team
