### ISSUE TITLE
bin so deppert

### ISSUE THREAD

**Issue by christian7877** [MicrosoftDocs/sql-docs.de-de#123]
„Applies to“-Verweise
Der Transact-SQL-Verweis enthält Artikel im Zusammenhang mit SQL Server (SQL Server 2008 und höher), Azure SQL-Datenbank und Azure Synapse Analytics (SQL Data Warehouse).
Am oberen Rand jedes Artikels befindet sich ein Abschnitt, der angibt, welche Produkte den Betreff des Artikels unterstützen. Wenn ein Produkt fehlt, ist das im Artikel beschriebene Feature in diesem Produkt nicht verfügbar. Beispielsweise wurden Verfügbarkeitsgruppen in SQL Server 2012 (11.x) eingeführt. Im Artikel Erstellen einer Verfügbarkeitsgruppe wird angegeben, dass die Funktion für SQL Server (SQL Server 2012 (11.x) und höher) gilt, weil sie nicht für SQL Server 2008, SQL Server 2008 R2 oder Azure SQL-Datenbank gilt.
Der allgemeine Betreff des Artikels könnte auf ein Produkt zutreffen, aber in einigen Fällen werden nicht alle Argumente unterstützt. Beispielsweise wurden Benutzer für eigenständige Datenbank in SQL Server 2012 (11.x)eingeführt. Verwenden Sie die Anweisung CREATE USER in einem SQL Server-Produkt, die Syntax WITH PASSWORD kann jedoch nicht mit älteren Versionen verwendet werden. Zusätzliche Applies to-Abschnitte werden in den entsprechenden Argumentbeschreibungen in den Text des Artikels eingefügt.
Weitere 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: f865e11f-ddd9-0812-6e86-9fa219d7eb09
* Version Independent ID: 42a8f774-e731-d336-b20c-f47747592d9e
* Content: [Transact-SQL-Syntaxkonventionen (Transact-SQL) - SQL Server](https://docs.microsoft.com/de-de/sql/t-sql/language-elements/transact-sql-syntax-conventions-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/language-elements/transact-sql-syntax-conventions-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/t-sql/language-elements/transact-sql-syntax-conventions-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by srvbpigh** [comment]
Hello, @christian7877
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @christian7877 

Wir freuen uns über Ihren Kommentar und bemühen uns, Ihre Erfahrungen mit docs.microsoft.com zu verbessern. Wir benötigen jedoch weitere Informationen, um auf Ihr Feedback eingehen zu können. Können Sie uns bitte nähere Informationen geben und Ihren Kommentar erläutern? 

Mit freundlichen Grüßen 

Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @christian7877 

Nochmals vielen Dank für Ihren Kommentar. 

Leider fehlen uns immer noch Informationen und wir können Ihr Feedback nicht bearbeiten. Wir schließen dieses GitHub-Problem jetzt, möchten Sie aber ermutigen, in Zukunft weiteres Feedback zu geben. 

Mit freundlichen Grüßen 

Microsoft DOCS International Team
