### ISSUE TITLE
How to install odbc drivers for SQL Server witout admin rights?

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/sql-docs.de-de#124]
I can't find how to install or use a "not to old" odbc driver for SQL Server on a Windows 10 target system without admin rights. Is this possible at all? Are there any of these no-admin-rights-required-drivers?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4123780b-93ac-e188-87a8-ffd4d5d37aa3
* Version Independent ID: fec60355-b6d1-1c41-bcd5-d202e0d09d90
* Content: [Systemanforderungen, Installation und Treiberdateien - SQL Server](https://docs.microsoft.com/de-de/sql/connect/odbc/windows/system-requirements-installation-and-driver-files?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/windows/system-requirements-installation-and-driver-files.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/connect/odbc/windows/system-requirements-installation-and-driver-files.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by srvbpigh** [comment]
Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @aisbergde 

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles. 

Microsoft DOCS International Team

**Comment by David-Engel** [comment]
@aisbergde Any user can use the ODBC drivers. But only admins can install them.
