### ISSUE TITLE
independed DATEPART(WEEKDAY, ...) 

### ISSUE THREAD

**Issue by samot1** [MicrosoftDocs/sql-docs.de-de#126]
If you need the WEEKDAY independend on the value set currently for DATEFIRST, you can use
`SELECT (DATEPART(WEEKDAY, GETDATE()) - 1 + @@DATEFIRST) % 7  AS weekday`

It will always return 1 for Monday, 2 for Tuesday ... 7 for Sunday, regardless to what DATEFIRST is set.

Maybe it could be added to the examples

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4d1c1cb1-feb7-d2d1-9b9f-6b3f8caff8d6
* Version Independent ID: c6caa07c-fb64-31e9-ed4f-36e367dfbaeb
* Content: [DATEPART (Transact-SQL) - SQL Server](https://docs.microsoft.com/de-de/sql/t-sql/functions/datepart-transact-sql?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DDE-DE%26k%3Dk(DATEPART_TSQL);k(sql13.swb.tsqlresults.f1);k(sql13.swb.tsqlquery.f1);k(DevLang-TSQL)%26rd%3Dtrue&view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/datepart-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/t-sql/functions/datepart-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by srvbpigh** [comment]
Hello, @samot1
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/sql-docs #5005](https://github.com/MicrosoftDocs/sql-docs/issues/5005) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @samot1 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/sql-docs/issues/5005

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
