### ISSUE TITLE
No bottle found for HOMEBREW_NO_ENV_FILTERING=1 ACCEPT_EULA=Y brew install msodbcsql17

### ISSUE THREAD

**Issue by wklopcar** [MicrosoftDocs/sql-docs.de-de#136]
OMEBREW_NO_ENV_FILTERING=1 ACCEPT_EULA=Y brew install msodbcsql17
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "msodbcsql17".
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 1c0de6fb-19ae-ff6f-8e73-ce66fa94bd64
* Version Independent ID: 34edd099-f4fe-4ac3-cdd4-abc87b35270b
* Content: [Installation von Microsoft ODBC Driver for SQL Server (macOS) - SQL Server](https://docs.microsoft.com/de-de/sql/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
@wklopcar Thanks for submitting feedback.

Did you run the other commands first? Because it sounds like you may not have.

```bash
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew tap microsoft/mssql-release https://github.com/Microsoft/homebrew-mssql-release
brew update
HOMEBREW_NO_ENV_FILTERING=1 ACCEPT_EULA=Y brew install msodbcsql17 mssql-tools
```

Regards,
David

**Comment by David-Engel** [comment]
This doesn't seem like a documentation issue. If you discover that this is actually a documentation issue, feel free to respond with more information.

#please-close
