### ISSUE TITLE
Exception in Language selection of german T-SQL help pages

### ISSUE THREAD

**Issue by Tornhoof** [MicrosoftDocs/sql-docs.de-de#42]
The german SQL docu page has an exception text in the language selection.
Example:
https://docs.microsoft.com/de-de/sql/t-sql/queries/select-order-by-clause-transact-sql

The exception is:
Liquid error: Object of type 'System.Char' cannot be converted to type 'System.String'.

![grafik](https://user-images.githubusercontent.com/7989549/36028549-b81c90d6-0d9f-11e8-81a2-cd55112cbd9b.png)

**Comment by CeciAc** [comment]
Hello, @Tornhoof,
 
Thank you for your feedback.
 
We are currently investigating this issue. We'll let you know of the resolution.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Assigned to project owner to check this issue
@ishasahni1

**Comment by ishasahni1** [comment]
@CeciAc This issue has been fixed and it no longer repro on the above url.
