### ISSUE TITLE
Using EKM with certificate-based Service Principal

### ISSUE THREAD

**Issue by HappyLuke** [MicrosoftDocs/sql-docs.de-de#81]
Hi,

thanks for this great documentation. In the documentation about using EKM with SQL Server ([https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault?view=sql-server-2017]()) I am missing one small, however very important information here. In Part 4 of the documentation you describe to use the Client ID and the Client Secret of a Service Prinicipal. However, my company does not allow password-based Service Principals, but only certificate-based Service Prinicipal because of control reasons.
Is it possible to use a certificate with the SQL Connector for Azure Key Vault and how? If not, do you plan to add this feature in a later release?

Thanks,

Lukas

**Comment by CeciAc** [comment]
Hello, @HappyLuke 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback here https://feedback.azure.com/forums/908035-sql-server/

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
