### ISSUE TITLE
Visualize key reference with in-database Python analytics for SQL

### ISSUE THREAD

**Issue by Fabi255** [MicrosoftDocs/sql-docs.de-de#86]
Hey, i'm new here and hope it's the right place for my question.

I got a Database with around 15 tables and key references between them. Now i want to visualize them like "Database Diagrams".
For more customization I would like to use in-database Python analytics for SQL, is there anywhere more dokumentation than the tutorial https://docs.microsoft.com/de-de/sql/advanced-analytics/tutorials/sqldev-py3-explore-and-visualize-the-data?view=sql-server-2017?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a6fd8a06-35b9-9fc3-4912-d9af48ab95e5
* Version Independent ID: 537915f7-101b-5783-d2a9-546fd7a54ce6
* Content: [Lektion 1 durchsuchen und Visualisieren von Daten mithilfe von Python und T-SQL – SQL Server-Machine Learning - SQL Server](https://docs.microsoft.com/de-de/sql/advanced-analytics/tutorials/sqldev-py3-explore-and-visualize-the-data?view=sql-server-2017)
* Content Source: [docs/advanced-analytics/tutorials/sqldev-py3-explore-and-visualize-the-data.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/advanced-analytics/tutorials/sqldev-py3-explore-and-visualize-the-data.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by CeciAc** [comment]
Hello, @Fabi255 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
