### ISSUE TITLE
Namen der Views

### ISSUE THREAD

**Issue by FrauDrDerWoche** [MicrosoftDocs/sql-docs.de-de#88]
Hier wird nicht definiert, welche Namen für eine View zulässig sind. Gibt es dort keine Zeichenbeschränkung oder werden bestimmte Zeichen abgelehnt?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 3aca8415-3cf0-347d-e36e-25ac4232adcf
* Version Independent ID: 05ce00aa-acfe-6936-4f56-a66691ce2dcc
* Content: [Erstellen von Sichten - SQL Server](https://docs.microsoft.com/de-de/sql/relational-databases/views/create-views?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/views/create-views.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/relational-databases/views/create-views.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by srvbpigh** [comment]
Hello, @FrauDrDerWoche
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/sql-docs #2692](https://github.com/MicrosoftDocs/sql-docs/issues/2692) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hallo, @FrauDrDerWoche

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation. 
Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/sql-docs/issues/2692
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
