### ISSUE TITLE
Problem of translation

### ISSUE THREAD

**Issue by Orti1964** [MicrosoftDocs/sql-docs.de-de#89]
Slightly incorrect. Either, the query is set to English then the result of DATENAME(WEEKDAY,XXX) should be 'Tuesday' or it is set to German an then, DATENAME(MONTH,XXX) should be 'OKTOBER'.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: fb496084-9556-a5a0-d158-64710423e11a
* Version Independent ID: 85a43da9-abbc-2f74-4ade-d0e3b5cecbdc
* Content: [DATENAME (Transact-SQL) - SQL Server](https://docs.microsoft.com/de-de/sql/t-sql/functions/datename-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/datename-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/t-sql/functions/datename-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by srvbpigh** [comment]
Hello, @Orti1964
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Orti1964 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/sql/t-sql/functions/datename-transact-sql?view=sql-server-2017

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
