### ISSUE TITLE
Funktion LTRIM wird im Baum als LSCHNEIDEN angezeigt 

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/sql-docs.de-de#93]
Im Navigationsbaum auf der linken Seite werden Teile von Funktionen gelegentlich und fälschlicherweise in Deutsch übersetzt. So wird beispielsweise "LTRIM" als "LSCHNEIDEN" angezeigt. 
Das gleiche betrifft falsche Anzeigen im Baum wie GROSSBUCHSTABEN
Da mir das jetzt schon öfter aufgefallen ist, dass im Baum schon falsche Übersetzungen aus englischen Funktionen angezeigt werden und das wohl keiner korrigiert, möchte ich mal darauf aufmerksam machen und darum bitten, dass Funktionen bitte im Baum immer im original geschrieben werden. Es braucht ja nur mal jemand den ganzen Baum unter Funktionen zu überprüfen.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7cadfbcd-359a-c40d-301a-adf1afe97db5
* Version Independent ID: 353edd4a-1bb5-904d-fe29-1a7850631840
* Content: [LTRIM (Transact-SQL) - SQL Server](https://docs.microsoft.com/de-de/sql/t-sql/functions/ltrim-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/functions/ltrim-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/t-sql/functions/ltrim-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by srvbpigh** [comment]
Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @aisbergde

Vielen Dank für Ihr Feedback. 
unsere Sprachexperten haben sich Ihren Vorschlag angesehen und diesen für gut befunden. Wir haben Ihr Feedback implementiert und im aktualisierten Artikel auf der Dokumentationsseite unter folgender Seite veröffentlicht: https://docs.microsoft.com/de-de/sql/t-sql/functions/ltrim-transact-sql?view=sql-server-2017
Vielen Dank für Ihren Beitrag zu diesem Artikel. Gerne können Sie auch weiterhin Feedback zu anderen Artikeln abgeben. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
