### ISSUE TITLE
UPPER wird im Baum als GROSSBUCHSTABEN übersetzt

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/sql-docs.de-de#94]
eine von mehreren Stellen, in denen Funktionen oder Teile von Funktionen automatisch und somit falsch in Deutsch übersetzt wurden, statt sie zu lassen, wie sie sind.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 5cbecceb-a220-362f-8da4-b16ba1586b7c
* Version Independent ID: f0182dc1-83e0-9dec-1518-407c2a850f02
* Content: [UPPER (Transact-SQL) - SQL Server](https://docs.microsoft.com/de-de/sql/t-sql/functions/upper-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/functions/upper-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/t-sql/functions/upper-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by srvbpigh** [comment]
Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @aisbergde
 
Vielen Dank für Ihr Feedback. 
unsere Sprachexperten haben sich Ihren Vorschlag angesehen und diesen für gut befunden. Wir haben Ihr Feedback implementiert und im aktualisierten Artikel auf der Dokumentationsseite unter folgender Seite veröffentlicht: XXX.  
Vielen Dank für Ihren Beitrag zu diesem Artikel. Gerne können Sie auch weiterhin Feedback zu anderen Artikeln abgeben. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
