### ISSUE TITLE
fehlender Teil in Übersetzung

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/sql-docs.de-de#98]
aktuell:
Beachten Sie, dass bei python zwischen Groß-und Kleinschreibung Die im Python-Skript (SQL_out, SQL_in) verwendeten Eingabe-und Ausgabevariablen müssen mit den Namen, die @input_data_1_name mit @output_data_1_nameund definiert sind, einschließlich der Groß-/Kleinschreibung entsprechen.
richtiger:
Beachten Sie, dass bei python zwischen Groß-und Kleinschreibung unterschieden wird. Die im Python-Skript (SQL_out, SQL_in) verwendeten Eingabe-und Ausgabevariablen müssen mit den Namen, die @input_data_1_name mit @output_data_1_nameund definiert sind, einschließlich der Groß-/Kleinschreibung entsprechen.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 37033ba2-66fb-1cf5-86e0-03b31c7ba7ac
* Version Independent ID: 2dc585ee-ac57-ac0d-cf03-12d623a18ff7
* Content: [Einfache python-Skripts erstellen und ausführen - SQL Server Machine Learning Services](https://docs.microsoft.com/de-de/sql/advanced-analytics/tutorials/quickstart-python-create-script?view=sql-server-2017)
* Content Source: [docs/advanced-analytics/tutorials/quickstart-python-create-script.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/advanced-analytics/tutorials/quickstart-python-create-script.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @garyericson
* Microsoft Alias: **garye**

**Comment by srvbpigh** [comment]
Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @aisbergde 

Vielen Dank für Ihr Feedback. 
unsere Sprachexperten haben sich Ihren Vorschlag angesehen und diesen für gut befunden. Wir haben Ihr Feedback implementiert und im aktualisierten Artikel auf der Dokumentationsseite unter folgender Seite veröffentlicht:  https://docs.microsoft.com/de-de/sql/advanced-analytics/tutorials/quickstart-python-create-script?view=sql-server-2017
Vielen Dank für Ihren Beitrag zu diesem Artikel. Gerne können Sie auch weiterhin Feedback zu anderen Artikeln abgeben. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
