### ISSUE TITLE
Auflisten von Python-Paketen - Code ruft ungültiges Attribut auf: pip.get_installed_distributions

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/sql-docs.de-de#99]
Beim Auführen des Code Beispiels kommt ein Fehler

EXECUTE sp_execute_external_script @language = N'Python'
    , @script = N'
import pip
for i in pip.get_installed_distributions():
    print(i)
'
GO

Ausgabe:

Msg 39004, Level 16, State 20, Line 31
A 'Python' script error occurred during execution of 'sp_execute_external_script' with HRESULT 0x80004004.
Msg 39019, Level 16, State 2, Line 31
An external script error occurred: 

Error in execution.  Check the output for more information.
Traceback (most recent call last):
  File "&lt;string&gt;", line 5, in &lt;module&gt;
  File "C:\ProgramData\MSSQLSERVER\Temp-PY\MSSQLSERVER01\79B5B5DD-C2DB-494E-9D05-E042D6397707\sqlindb_0.py", line 33, in transform
    for i in pip.get_installed_distributions():
AttributeError: module 'pip' has no attribute 'get_installed_distributions'

SqlSatelliteCall error: Error in execution.  Check the output for more information.
STDOUT message(s) from external script: 
SqlSatelliteCall function failed. Please see the console output for more information.
Traceback (most recent call last):
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\computecontext\RxInSqlServer.py", line 605, in rx_sql_satellite_call
    rx_native_call("SqlSatelliteCall", params)
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\RxSerializable.py", line 375, in rx_native_call
    ret = px_call(functionname, params)
RuntimeError: revoscalepy function failed.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 37033ba2-66fb-1cf5-86e0-03b31c7ba7ac
* Version Independent ID: 2dc585ee-ac57-ac0d-cf03-12d623a18ff7
* Content: [Einfache python-Skripts erstellen und ausführen - SQL Server Machine Learning Services](https://docs.microsoft.com/de-de/sql/advanced-analytics/tutorials/quickstart-python-create-script?view=sql-server-2017)
* Content Source: [docs/advanced-analytics/tutorials/quickstart-python-create-script.md](https://github.com/MicrosoftDocs/sql-docs.de-de/blob/live/docs/advanced-analytics/tutorials/quickstart-python-create-script.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @garyericson
* Microsoft Alias: **garye**

**Comment by srvbpigh** [comment]
Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by aisbergde** [comment]
the code example from your documentation is not supported, I found the better example here https://github.com/ARMmbed/mbed-cli/issues/657

Here is working code:

EXECUTE sp_execute_external_script @language = N'Python'
    , @script = N'
from pip._internal.utils.misc import get_installed_distributions
for i in get_installed_distributions():
    print(i)
'
GO

**Comment by dphansen** [comment]
@aisbergde I am not able to replicate the error that you are getting. Please open a ticket with Microsoft Support at [SQL Server help and feedback](https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-2017) to resolve this issue.

@CeciAc Please close this GitHub issue. There is no change to the docs.

**Comment by lichasu** [comment]
Closing as requested.

Thanks!

**Comment by aisbergde** [comment]
Closing the request - how easy. Why I give you valuable feedback if you ignore it?
I even added a link where you can find that this example is outdated in current versions of Python. 
I think you can't replicate because by default you use an older version of Python which is by default installed with sql server. I was not able to install Python using the regular setup (it's another bug that the setup can't handle issues with the download of the Python installer components and can't be repaired). That's why I installed the latest Microsoft Machine Learning Server which has a newer Python version where this code example will not work to also "repair" the sql server installation. 
I even sent you the right code which will work also with newer Python versions. But of course you can close the topic and the example, wich is working now, will be obsolete in the future.

**Comment by dphansen** [comment]
@aisbergde SQL Server 2017 has pip version 9 included, which uses `pip.get_installed_distributions`. This article covers SQL Server 2017 with pip version 9.

The change to `pip.get_installed_distributions` happened in version 10, according to the [pip release note for version 10](https://pip.pypa.io/en/stable/news/#b1-2018-03-31):

> Move all of pip’s APIs into the pip._internal package, properly reflecting the fact that pip does not currently have any public APIs.

There is also a note about this in [the pip User Guide](https://pip.pypa.io/en/stable/user_guide/#using-pip-from-your-program):

> As noted previously, pip is a command line program. While it is implemented in Python, and so is available from your Python code via import pip, you must not use pip’s internal APIs in this way.

It is not recommended to use the `pip._internal package`, as this is the internal API.

Another method is using `pkg_resources` as described in the [Get Python package information](https://docs.microsoft.com/en-us/sql/advanced-analytics/package-management/python-package-information?view=sql-server-2017#list-all-installed-python-packages) how-to guide. You can also use the `list` function in **sqlmlutils**, as documented on the [GitHub repo](https://github.com/microsoft/sqlmlutils/tree/master/Python). We are in the process of bringing these methods into our documentation.
